 export const DUMMY_DATA: any[] = [
  {
    linea: 1,
    cuenta: '99999999999',
    beneficiario: 'Jane Cooper',
    tipo: 'Beneficiario Interno',
    banco: 'BAC',
    monto: '500000',
    moneda: 'USD',
  },
  {
    linea: 2,
    cuenta: '999999999',
    beneficiario: 'Peter Parker',
    tipo: 'Beneficiario Externo',
    banco: 'Cuscatlán',
    monto: '500000',
    moneda: 'USD',
  },
  {
    linea: 3,
    cuenta: '154947949',
    beneficiario: 'Mary Jane',
    tipo: 'Beneficiario Interno',
    banco: 'ScotiaBank',
    monto: '500000',
    moneda: 'USD',
  },
  {
    linea: 4,
    cuenta: '99999999999',
    beneficiario: 'Joe Morrison',
    tipo: 'Beneficiario Interno',
    banco: 'BAC',
    monto: '500000',
    moneda: 'USD',
  },
  {
    linea: 5,
    cuenta: '22422525252',
    beneficiario: 'Andrea Moratta',
    tipo: 'Beneficiario Interno',
    banco: 'BAC',
    monto: '500000',
    moneda: 'USD',
  },
  {
    linea: 6,
    cuenta: '1212121212121',
    beneficiario: 'Julia Roberts',
    tipo: 'Beneficiario Externo',
    banco: 'New Bank Lta',
    monto: '500000',
    moneda: 'USD',
  },
  {
    linea: 7,
    cuenta: '6464646464',
    beneficiario: 'Mike Pérez',
    tipo: 'Beneficiario Externo',
    banco: 'Cuscatlán',
    monto: '500000',
    moneda: 'USD',
  },
  {
    linea: 8,
    cuenta: '99999999999',
    beneficiario: 'Jenifer Black',
    tipo: 'Beneficiario Interno',
    banco: 'ScotiaBank',
    monto: '500000',
    moneda: 'USD',
  },
];
